### PR TITLE
change method to detect current shell

### LINKED ISSUE #22: Unable to build firmware
**Problem Description**
I was following the instructions, but was unable to build the firmware through Arduino IDE (1.8.2)

The sketchbook is set as `~/catkin_ws/src/versavis/firmware`

The error log is as the following. 
```
Arduino: 1.8.2 (Linux), Board: "VersaVIS"

Build options changed, rebuilding all
In file included from /home/jaeyoung/catkin_ws/src/versavis/firmware/libraries/versavis/src/Imu.h:17:0,
                 from /home/jaeyoung/catkin_ws/src/versavis/firmware/libraries/versavis/src/ADIS16448BMLZ.h:33,
                 from /home/jaeyoung/catkin_ws/src/versavis/firmware/versavis/versavis.ino:15:
/home/jaeyoung/catkin_ws/src/versavis/firmware/libraries/versavis/src/Sensor.h:19:10: fatal error: versavis/ImuMicro.h: No such file or directory
 #include <versavis/ImuMicro.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board VersaVIS.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```
`ImuMicro.h` seems to be something that is built afterwards and added into the `catkin_ws/devel/versavis`, but arduinoIDE is unable to find it

### PR DESCRIPTION
**Pull request by floriantschopp**
necessary to fix #22 and #28

### CODE REVIEW

File: firmware/setup.sh [hunk 1]
```diff
@@ -1,5 +1,5 @@
 catkin build versavis
-shell=`grep ^$(id -un): /etc/passwd | cut -d : -f 7- |  cut -d'/' -f4-`
+shell=`echo $0 | cut -c 2-`
```
Comment (LBern) [inline firmware/setup.sh]: small test script (test.sh) on my computer: 
```
shell=`echo $0 | cut -c 2-`                                                     
echo "setup.$shell"
```
then `./test.sh` on my computer prints: 
`setup./test.sh`

I think you rather wanted to have this:
```
shell=`echo $0 | rev | cut -c 1-2 | rev`                             
echo "setup.$shell"
```

which prints then 
`setup.sh`

But I'm not sure why you want take `$0`?

**Comment by LBern** [comment]
Maybe it is better to hardcode the shell, i.e.

`shell="zsh"  # default zsh, as this is the best shell ;)`

**Review by LBern — APPROVED** [review]
lgtm
